[package]
name = "der-des-ders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
